### PR TITLE
Update unpack.sh

### PR DESCRIPTION
**Pull request by PEAKYCOMMAND**
removed error "mv"

### CODE REVIEW

**Comment by PEAKYCOMMAND** [comment]
Add

**Review by PEAKYCOMMAND — COMMENTED** [review]
Mv correct

**Comment by PEAKYCOMMAND** [comment]
Mv correct

**Comment by CRYZUEZIN** [comment]
the last one, right?

**Comment by PEAKYCOMMAND** [comment]
Yes


Em sex., 2 de dez. de 2022 7:40 PM, Josué Martins ***@***.***>
escreveu:

**Pull request closed without merging**
